### ISSUE TITLE
Running `npm install` after sequelize-simple-pagination was installed fails with EISGIT

### ISSUE THREAD

**Issue by Danita** [eugenechen0514/sequelize-simple-pagination#3]
I had installed and used sequelize-simple-pagination without problems. Then I wanted to install a new dependency on my project using `npm install` but it failed with:

```
$ npm install forme --save
npm ERR! path G:\Documents\Projects\my_project\node_modules\sequelize-simple-pagination
npm ERR! code EISGIT
npm ERR! git G:\Documents\Projects\my_project\node_modules\sequelize-simple-pagination: Appears to be a git repo or submodule.
npm ERR! git     G:\Documents\Projects\my_project\node_modules\sequelize-simple-pagination
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-12-10T11_05_57_865Z-debug.log
```

After a bit of investigation I found that this error usually occurs when a dependency comes with a `.git` directory. So something like `rm -rf node_modules/*/.git/` solves the problem temporarily. But there should be no `.git` on the module to begin with.

Thanks!

**Comment by eugenechen0514** [comment]
I fixed the problem. 
There is a file `READMEsample`  at `node_modules/sequelize-simple-pagination/.git/hooks`. 

Please upgrade to **0.1.1** or reinstall, thx.

**Comment by Danita** [comment]
Thank you!
